### ISSUE TITLE
Running a GraphQL API on Dgraph, a native distributed graph database

### ISSUE THREAD

**Issue by pawanrawal** [graphqlsydney/graphqlsydney#1]
I'll talk about how easy it is to get started with a GraphQL API served by Dgraph (https://github.com/dgraph-io/dgraph) which is an open source distributed graph database. We'll also look at why this is better than serving a GraphQL API powered by a relational database and how it solves the N+1 problem. The talk would include a live demo in which we'll build a real world application from scratch where we only define the GraphQL types for our application and all the queries/mutations are auto-generated by Dgraph.

I'd like to present this talk at the November meetup. I am available on Twitter at https://twitter.com/pawan_rawal. The talk would be 30 mins in duration.

**Comment by paulfioravanti** [comment]
Thanks very much @pawanrawal! You're locked in as a speaker for November!

**Comment by pawanrawal** [comment]
Thanks @paulfioravanti. When do you guys plan to list the talks on the meetup event? I was looking forward to share the invite for the meetup with friends.

**Comment by paulfioravanti** [comment]
Hey @pawanrawal, we typically put up event details once we've gained enough speakers for the event. As of this writing, you're currently the only one, so we haven't updated the event description just yet. But, regardless, we'll probably update it on the weekend. You can certainly share the meetup link with your friends (https://www.meetup.com/GraphQL-Sydney/events/260841085/), and let them know they'll see your name up there soon :)

**Comment by joshprice** [comment]
This is now updated.

**Comment by paulfioravanti** [comment]
Thanks for presenting @pawanrawal! If you want to share your presentation materials, tweet out a link to them at `@graphqlsydney` and we'll give them a retweet.
