### ISSUE TITLE
Batch queries for GraphQL to avoid N+1 issues

### ISSUE THREAD

**Issue by bapu-nexl** [graphqlsydney/graphqlsydney#10]
- I would like to demonstrate the challenges GrapghQL presents wrt fetching association data and how it leads to N+1 db queries and makes the GraphQL query slow. I will use Rails Activerecord for use case.

 - I would also like to talk about summary of [graphql-batch](https://github.com/Shopify/graphql-batch) gem to find a solution to mitigate this issue.

- I would like to present on Aug 20th or later
 
Picture:
https://avatars1.githubusercontent.com/u/47874398?s=400&u=c97e3543ad24dd22b4ff2d70fae6bbd3e02ac251&v=4

**Comment by paulfioravanti** [comment]
Hi Bapu, thanks for the issue! Is this you? https://www.linkedin.com/in/bapu-sethi-1a66534/

**Comment by bapu-nexl** [comment]
> Hi Bapu, thanks for the issue! Is this you? https://www.linkedin.com/in/bapu-sethi-1a66534/

Yes :)

**Comment by paulfioravanti** [comment]
Okay, cool, thanks :) If we get a full-length talk as well for August 20, we'll schedule you in. Otherwise, we may end up needing to schedule you up for the next meetup. Unless you want to do a full-length talk rather than a lightning talk...?

**Comment by bapu-nexl** [comment]
> Okay, cool, thanks :) If we get a full-length talk as well for August 20, we'll schedule you in. Otherwise, we may end up needing to schedule you up for the next meetup. Unless you want to do a full-length talk rather than a lightning talk...?

The scope of this presentation I prepared is not much, so I would prefer a lightning talk.

**Comment by paulfioravanti** [comment]
All good :+1: If we get a full-length talk by this evening, I'll schedule you up for Thursday. Otherwise, I'll set the milestone for this talk to the next meetup.

**Comment by paulfioravanti** [comment]
We'll be doing the [next meetup in November](https://www.meetup.com/GraphQL-Sydney/events/272890969), so I've scheduled you up for then, so you've still got lots of time to prepare :) I'll be making an announcement soon about a change of cadence for the meetup, so that's why the re-schedule has happened. Hope that's okay, but if not, please reach out.

**Comment by bapu-nexl** [comment]
> We'll be doing the [next meetup in November](https://www.meetup.com/GraphQL-Sydney/events/272890969), so I've scheduled you up for then, so you've still got lots of time to prepare :) I'll be making an announcement soon about a change of cadence for the meetup, so that's why the re-schedule has happened. Hope that's okay, but if not, please reach out.

Thats perfect, Paul.

**Comment by paulfioravanti** [comment]
Hi @bapu-nexl, just confirming that you're still okay to do your lightning talk this month. Please confirm and I'll add your talk details to the meetup description.

**Comment by bapu-nexl** [comment]
> Hi @bapu-nexl, just confirming that you're still okay to do your lightning talk this month. Please confirm and I'll add your talk details to the meetup description.

Yes Paul, looking forward to it

**Comment by paulfioravanti** [comment]
Thanks for your talk yesterday, @bapu-nexl! It's now been published to the GraphQL Australia YouTube channel: https://www.youtube.com/watch?v=6WZ-3YF1MSM&t=2s
