### ISSUE TITLE
Production Ready GraphQL: Rapid Development of GraphQL APIs using AWS

### ISSUE THREAD

**Issue by taylor-zr** [graphqlsydney/graphqlsydney#11]
Thanks for proposing a talk for GraphQL Sydney!

Please provide the following information:

- Name of talk (in the title field)
- Brief summary of the talk content
Building your first production application using GraphQL can seem overwhelming. In this talk you'll learn how you can build out a reliable, scalable, and extensible GraphQL API in a matter of minutes using AWS Amplify and AWS AppSync. You'll also learn how to leverage interesting features like subscriptions and we'll touch on how to bake complex behavior into your API calls. 
- Which month's meetup you would like to present at
November
- Length of talk (Max 30 minutes, but feel free to take less time; the more succinct, the better!)
30 mins
- Your Twitter username (if you have one)
- Link to, or upload of, a photo of yourself that will appear in the meetup slide deck (if you don't specify one, we'll see if we can find one from your social media accounts)
![robertson-taylor](https://user-images.githubusercontent.com/43951068/91687982-48fe2300-eba4-11ea-8139-b9643c9c8f7d.jpeg)

**Comment by paulfioravanti** [comment]
Hi @taylor-zr, thanks for submitting a presentation! I'm happy to schedule you up for November, and then we can confirm closer to the date that you're still good to go. One thing, though, what is your full name? I couldn't discern that from your Github account :)

**Comment by taylor-zr** [comment]
Hey Paul! My full name is Robertson Taylor

**Comment by paulfioravanti** [comment]
Thanks, Robertson! Let's reserve your spot!

**Comment by paulfioravanti** [comment]
Hey @taylor-zr, just confirming that you're still good to go for your talk at this month's meetup. Please confirm and I'll add your talk details to the meetup description.

**Comment by taylor-zr** [comment]
Hey Paul! Yup, good to go!

Rob

**Comment by taylor-zr** [comment]
Hey Paul! Just wondering where I should join up to test mic/webcam etc.

Feel free to send me an email

**Comment by paulfioravanti** [comment]
Thanks very much for the talk yesterday, @taylor-zr! It has now been published to the GraphQL Australia YouTube channel: https://www.youtube.com/watch?v=V6xBV1tw40Q

If you end up making your slide deck public (via Slideshare, Speakerdeck etc), please post a link to it here and we'll tweet it out from the GraphQL Sydney Twitter account.
