### ISSUE TITLE
API Management for GraphQL

### ISSUE THREAD

**Issue by fazlan-nazeem** [graphqlsydney/graphqlsydney#12]
API Management is a vital platform for an organization to expose its services in a secured and governed manner. However, the challenges and concerns associated with exposing GraphQL services for application developers are different from the traditional REST or SOAP-based endpoints. This introduces a need to adopt an API management platform that specifically treats GraphQL characteristics as first-class citizens.

The session will cover,

- What API Management means
- What to expect from an API Management platform to manage GraphQL services
- A short demonstration

I would like it if the organizers can set up this talk at end of November or early December. 

Twitter: https://twitter.com/fazlan077
Linkedin: https://www.linkedin.com/in/fazlannazeem/

**Comment by paulfioravanti** [comment]
Hi @fazlan-nazeem, thanks very much for the submission!

Our next meetup is on [November 11](https://www.meetup.com/GraphQL-Sydney/events/272890969/) from 6pm AEDT, so if you are able to do your talk then, I'm more than happy to schedule you in. Could you please mention how long your presentation is, keeping in mind to try and keep it to a maximum of 30 minutes.

If November does not work, our next meetup is scheduled for February 2021 (our cadence is once a quarter), so if it can wait until then, I'm happy to mark this issue against that milestone and follow up with you closer to the date.

**Comment by fazlan-nazeem** [comment]
Hey @paulfioravanti , thank you for accepting the talk. Unfortunately, November 11th coincides with my vacation period. Therefore I would like to have a slot for the February 2021 meetup. 

P.S: the talk will be for 25-30 minutes 

Thank you in advance.

**Comment by paulfioravanti** [comment]
Great to hear! I'll mark this issue with the February 2021 milestone and reach out again early next year to confirm that you're still good to present.

**Comment by fazlan-nazeem** [comment]
Hi @paulfioravanti 

Just checking whether a date is finalized for the meetup.

**Comment by paulfioravanti** [comment]
Hi @fazlan-nazeem, 

We're currently [scheduled for February 10](https://www.meetup.com/GraphQL-Sydney/events/275488256/) at 6pm AEDT. Does that still work okay for you?

**Comment by fazlan-nazeem** [comment]
Hi @paulfioravanti 

Yes, the date and time work for me. You can go ahead and schedule the talk.

**Comment by fazlan-nazeem** [comment]
Slides for the talk https://www.slideshare.net/wso2.org/graphql-sydeny-api-management-for-graphql

**Comment by paulfioravanti** [comment]
Thanks very much for your talk yesterday, @fazlan-nazeem! Your talk is now published up on the GraphQL Australia YouTube channel: https://www.youtube.com/watch?v=VUdB4B4mXzg
