### ISSUE TITLE
Major time saving with Hasura

### ISSUE THREAD

**Issue by limenutt** [graphqlsydney/graphqlsydney#13]
### Brief summary
We've recently launched a big project powered by Hasura and would like to share this experience.
We would like to focus on the approach we took and the tools we used to save the development time.
Additionally, we will share the problems we've faced and our solutions.
The stack is: Angular + Hasura + serverless (Azure)

### Length
~20 mins

### Meetup
10/2/2021

### The speaker

Pavel Kostenko, a fullstack engineer working for [Skychute](https://skychute.com.au/).
@poul-kg
LinkedIn: https://www.linkedin.com/in/pavel-kostenko-a160a018/

**Comment by paulfioravanti** [comment]
Hi @limenutt, thanks very much for the submission! Happy to have whomever ends up doing this talk on the speaker lineup for February, so I'll lock this talk in. When that has been decided, please update this issue with all of their information (name, photo, Twitter/social media etc).

**Comment by limenutt** [comment]
Thank you for the confirmation, @paulfioravanti ! Sure, I'll update you here with the speaker details.

**Comment by limenutt** [comment]
Hi @paulfioravanti , I've updated the description with the speaker. I think you can take the photo from Linkedin, otherwise please let me know if you are after particular photo format.

**Comment by paulfioravanti** [comment]
Great, thanks, @limenutt !

**Comment by paulfioravanti** [comment]
Thanks very much for your talk and awesome demo-ing skills yesterday @poul-kg! Your talk has now been published to the GraphQL Australia YouTube channel: https://www.youtube.com/watch?v=VUdB4B4mXzg
