### ISSUE TITLE
Using MicroProfile GraphQL with Helidon and Coherence

### ISSUE THREAD

**Issue by tmiddlet2666** [graphqlsydney/graphqlsydney#14]
**Brief summary**
Project Helidon, a set of Java Libraries for writing microservices, now supports MicroProfile GraphQL Spec 1.0.3.
In this presentation Tim will provide an overview of the MP-GraphQL Spec, how it is implemented in Helidon and 
how to easily create GraphQL endpoints using Coherence Data-Grid as a backend source.

**Length**
~20-30 mins

**Meetup**
May 12

**The speaker**
Tim  Middleton - Software Engineer with the Coherence Development team at Oracle

https://www.linkedin.com/in/tim-middleton-23056a3/

**Comment by paulfioravanti** [comment]
Thanks very much, @tmiddlet2666! Let's schedule you up for May! 🎉

**Comment by tmiddlet2666** [comment]
Presentation PDF.
[GraphQL-Sydney.pdf](https://github.com/graphqlsydney/graphqlsydney/files/6465162/GraphQL-Sydney.pdf)

**Comment by paulfioravanti** [comment]
@tmiddlet2666 your talk is now up on the GraphQL Australia YouTube channel: https://www.youtube.com/watch?v=6QquGSTM6n0 Thanks very much, and if you end up putting your slides up on Slideshare/Speakerdeck etc, please let us know the link and we'll tweet it out.
