### ISSUE TITLE
Front-end Frameworks, Back-end Databases, and GraphQL

### ISSUE THREAD

**Issue by a-chocolate-bear** [graphqlsydney/graphqlsydney#15]
Thanks for proposing a talk for GraphQL Sydney!

Please provide the following information:

- Name of talk (in the title field)
- Brief summary of the talk content
- With more than 100M pulls, the Hasura GraphQL Engine has become an increasingly popular way to instantly generate GraphQL endpoints on your data stored in Postgres. But what happens when you refactor the core to generalize interfaces, add additional databases, and supplement existing features? In this talk Adron Hall will share the story of GraphQL broadly, through the lens of Hasura, and do so in a way that speaks to a variety of experience levels and technical abilities. You will learn:
* What are the technical considerations you should be aware of when evaluating your own API strategy?
* How did Hasura approach such a major refactor?
* Where do you get started when wanting to use GraphQL with the frontend framework of your choice
- Which month's meetup you would like to present at
- May 2021
- Length of talk (Max 30 minutes, but feel free to take less time; the more succinct, the better!)
- 20 minutes
- Your Twitter username (if you have one)
- @praveenweb
- Link to, or upload of, a photo of yourself that will appear in the meetup slide deck (if you don't specify one, we'll see if we can find one from your social media accounts)
- https://twitter.com/praveenweb

**Comment by paulfioravanti** [comment]
Hi @a-chocolate-bear, thanks very much for your submission! You are locked in for the May meetup!

**Comment by paulfioravanti** [comment]
@a-chocolate-bear your talk is now up on the GraphQL Australia YouTube channel: https://www.youtube.com/watch?v=LxK9g0qmqpI

If you end up making your slide deck public somewhere like Slideshare or Speakerdeck, please tweet them out, tagging `@graphqlsydney` and we'll make sure to give them a re-tweet. Thanks very much!
