### ISSUE TITLE
GraphQL APIs for Postgres with `pg_graphql`

### ISSUE THREAD

**Issue by rellen** [graphqlsydney/graphqlsydney#18]
- Brief summary of the talk content: `pg_graphql` by Supabase (https://github.com/supabase/pg_graphql) is a lightweight extension to Postgres that adds a GraphQL layer over your databases, in the same style as PostgREST.  This talk will go over how to get started with `pg_graphql`.
- Month: When it is out of beta
- 15 - 30 mins

**Comment by paulfioravanti** [comment]
Thanks, @rellen! I guess we'll schedule this up for whenever that release happens!

**Comment by paulfioravanti** [comment]
Locked in this talk for the now-rescheduled May 18th meetup :+1:
