### ISSUE TITLE
GraphQL: the unknown and maybe surprising

### ISSUE THREAD

**Issue by andimarek** [graphqlsydney/graphqlsydney#2]
A talk about rather unknown GraphQL features.

My twitter: twitter.com/andimarek

For the meetup on 20.11.2019. Full talk, ca. 30min.

**Comment by paulfioravanti** [comment]
Thanks, @andimarek! You're in!

**Comment by paulfioravanti** [comment]
Thanks for presenting @andimarek ! If you want to share your presentation materials, tweet out a link to them at `@graphqlsydney` and we'll give them a retweet.
