### ISSUE TITLE
Getting Started with GraphQL through Gatsby.js

### ISSUE THREAD

**Issue by biancapower** [graphqlsydney/graphqlsydney#21]
## Brief summary of the talk content

Gatsby.js is a popular React-based static site generator that uses GraphQL to manage complex data. In this talk we'll look at how working with Gatsby can be a great way to get familiar with GraphQL, and do some live exploration of GraphQL queries in a simple Gatsby site.

## Which month's meetup you would like to present at
December, or any time after that

## Will the talk be given in-person or online
In person

## Length of talk (Max 30 minutes, but feel free to take less time; the more succinct, the better!)
Around 20 mins

## Your Twitter username (if you have one)
[20by31](https://twitter.com/20by31)

## Link to, or upload of, a photo of yourself that will appear in the meetup slide deck (if you don't specify one, we'll see if we can find one from your social media accounts)
[Profile pic](https://media-exp1.licdn.com/dms/image/C4E03AQF5F2oaMZliEw/profile-displayphoto-shrink_400_400/0/1616531896686?e=1674691200&v=beta&t=Puabx_a6zEFCoK-yfW0YJwe3Jr3o5QdyFHCWO7l0qp4)

**Comment by paulfioravanti** [comment]
Hi @biancapower! Thanks for submitting a talk, and we'd love to have you at the next meetup! Consider this talk locked in!

**Comment by biancapower** [comment]
> Hi @biancapower! Thanks for submitting a talk, and we'd love to have you at the next meetup! Consider this talk locked in!

Thanks @paulfioravanti , looking forward to it!

**Comment by joshprice** [comment]
Video is now up, thanks for a great talk @biancapower!

https://youtu.be/hiaFCqvTeA0
