### ISSUE TITLE
How I Learned to Stop Worrying and Love Low-Code

### ISSUE THREAD

**Issue by sordina** [graphqlsydney/graphqlsydney#22]
Summary of Information:

- Name of talk: `How I Learned to Stop Worrying and Love Low-Code`
- Brief summary of the talk content:
     > In this talk I'll describe a database-first approach to application design
     > that greatly increases frontend velocity and
     > puts business-logic back in the driver's seat.
     > 
     > Pleased to meet you, I'm Lyndon and have been working at Hasura for
     > almost 3 years as a senior engineer and have contributed to many of the
     > key features that have come out during that time. You might enjoy my
     > perspective on why this style of solution can provide a way to think
     > differently about application backend development.
- Which month's meetup you would like to present: April
- Will the talk be given in-person or online: Online
- Where you can be found on the internet: https://www.linkedin.com/in/lyndon-maydwell-01455723/
- Link to, or upload of, a photo of yourself that will appear in the meetup slide deck:

<img width="417" alt="image" src="https://user-images.githubusercontent.com/92299/220016911-9d0b2dad-c11e-4902-a9e3-d5f351a398d6.png">

**Comment by paulfioravanti** [comment]
Thanks for the submission, @sordina! The next meetup is on March 8th, and the next one won't be until June. Just to confirm, did you mean to put March as the meetup you'd like to present in?

**Comment by sordina** [comment]
Hi @paulfioravanti

March is ok for me if there's no April meetup scheduled. Thanks!

**Comment by paulfioravanti** [comment]
Great, thanks, @sordina! You're locked in for March 8!

**Comment by joshprice** [comment]
Video has been uploaded https://youtu.be/tSvlt4M5zqI

Thanks for an entertaining talk!

**Comment by sordina** [comment]
Thanks so much @joshprice !
