### ISSUE TITLE
GraphQL with Java and Spring

### ISSUE THREAD

**Issue by dondonz** [graphqlsydney/graphqlsydney#24]
Hey! Long time no see 😄 

@paulfioravanti a long time ago you suggested coming up with a GraphQL talk and I've finally got one! 

Since I last saw you, I've gone a bit mad for GraphQL! These days I help out with maintaining @graphql-java, and very soon I'll be publishing a book about the GraphQL Java library and the official Spring integration built on top of it, [Spring for GraphQL](https://docs.spring.io/spring-graphql/docs/current/reference/html/).

**Brief summary of the talk content**
I was thinking of a live coding session where we build a Java GraphQL service together from scratch. It's much faster than you think! It will be 10-15 mins in length, I can give a better indication of timing after I get my script finalised.

**Which month's meetup you would like to present at**
The next meetup (would it be June?)

**Will the talk be given in-person or online**
In person

**Where you can be found on the internet (e.g. personal website, social media account links etc)**
GitHub: https://github.com/dondonz
LinkedIn: https://www.linkedin.com/in/donnazhou/

**Link to, or upload of, a photo of yourself that will appear in the meetup slide deck (if you don't specify one, we'll see if we can find one from your social media accounts)**
I've got a special profile pic for this presentation - can I email it to you?

**Comment by paulfioravanti** [comment]
Hey @dondonz, sounds like you've been incredibly busy with GraphQL lately! I've stepped away from managing meetups, but I'm sure @joshprice can take care of scheduling this up!

**Comment by joshprice** [comment]
Our next meetup will be in Feb 2024, would you be interested in doing this talk or something like it then?

**Comment by dondonz** [comment]
Hello, thanks for the offer but I won't be able to do the talk. However if anyone wants to see what I would have spoken about, I helped write the Spring official tutorial: https://spring.io/guides/gs/graphql-server/
