### ISSUE TITLE
Visualizing the N+1 data fetching in GraphQL

### ISSUE THREAD

**Issue by flexdinesh** [graphqlsydney/graphqlsydney#25]
## Brief Summary

A visual walkthrough of the N+1 data fetching problem and why it's more prominent in GraphQL than other tools. I have published an [npm package - next-batch](https://github.com/flexdinesh/next-batch) to help solve this problem in GraphQL resolvers. I would like to walk through that package and showcase how it works and how it compares to the popular [dataloader](https://github.com/graphql/dataloader) package that we all love and use in all our GraphQL implementations.

Here's the blog post version of the talk: https://dineshpandiyan.com/blog/graphql-n+1

## Details

- Which month's meetup you would like to present at? **April**
- Will the talk be given in-person or online? **In-person**
- Length of talk: **20-30 mins**
- Where you can be found on the internet? [twitter/flexdinesh](https://twitter.com/flexdinesh)
- Photo: [link to photo](https://dineshpandiyan.com/images/dinesh-highres.png)

**Comment by mbuhot** [comment]
Hi @flexdinesh 👋 

We'd love to have you present at the next GraphQL Sydney meetup.
Are you available to present on the evening of Tuesday 5th December?

Thanks!

**Comment by flexdinesh** [comment]
Hey @mbuhot 👋 Yes, I'll be available. Lock it in. 🙌

**Comment by mbuhot** [comment]
Thanks @flexdinesh, you'll be the second speaker at the December meetup: https://www.meetup.com/graphql-sydney/events/297415925/

**Comment by joshprice** [comment]
Rescheduled for Feb 2024, date TBD

**Comment by mbuhot** [comment]
Thanks @flexdinesh, really enjoyed the talk 👍 👍 
The video is now available on YouTube https://www.youtube.com/watch?v=TK4N7wXAYZA
