### ISSUE TITLE
 GraphQL Codegen: From Database to API

### ISSUE THREAD

**Issue by tnodell** [graphqlsydney/graphqlsydney#26]
Please provide the following information:

- Name of talk (in the title field): GraphQL Codegen: From Database to API
- Brief summary of the talk content:
We've created an open-source tool, Graphweaver, which allows you to introspect a datasource, generate the resolvers and entities, and then generating the GraphQL schema. The focus will be on GraphQL schema and how that works, the problems it solves and using the introspection query and then creating a map of those relationships in a templating language to get your desired output.

Here is a blog format of the talk:
[https://dev.to/tnodell/exploring-the-benefits-of-graphql-code-gen-22gd
](https://dev.to/tnodell/exploring-the-benefits-of-graphql-code-gen-22gd
)
- Which month's meetup you would like to present at: 
Next available meetup.
- Will the talk be given in-person or online
In Person
- Where you can be found on the internet (e.g. personal website, social media account links etc):
https://taylornodell.com/
https://github.com/nodes777
https://www.instagram.com/tayloredtotaylor/

- Link to, or upload of, a photo of yourself that will appear in the meetup slide deck (if you don't specify one, we'll see if we can find one from your social media accounts)
[https://avatars.githubusercontent.com/u/81122022?v=4](https://avatars.githubusercontent.com/u/81122022?v=4
)

**Comment by mbuhot** [comment]
Hi @tnodell 👋 

We'd love to have you present at the next GraphQL Sydney meetup, scheduled for the evening of Tuesday 5th December.
Can you please confirm your availability on that date? 

Thanks!

**Comment by tnodell** [comment]
@mbuhot, yes that date works for me. Let's sync up via email.

**Comment by mbuhot** [comment]
Thanks @tnodell 👍  You'll be the 3rd speaker at the December Meetup https://www.meetup.com/graphql-sydney/events/297415925/

**Comment by mbuhot** [comment]
Thanks again @tnodell, the recording of the talk is now live on YouTube: https://www.youtube.com/watch?v=kAf832rfKiI
