### ISSUE TITLE
Behind the Queries: Debugging GraphQL Like a Pro

### ISSUE THREAD

**Issue by danstarns** [graphqlsydney/graphqlsydney#27]
Hey Sydney Folk!  🦘

Here is my submission for the upcoming event on the 5th of December. 

"When resolving a GraphQL query, lots of operations could be happening under the hood, for example, you could be:

* Making database calls
* Invoking nested resolvers
* Calling other subgraphs
* Linking in your custom business logic

From button click to database call, how much do you really know what's going on? With tools like Network Inspector only giving you the first part of the equation ‘browser to server’, you are left to your own devices.

Join Dan Starns in Debugging GraphQL Like a Pro."

You can find me on Twitter https://twitter.com/dan_starns and you can use my profile photo there, I am representing my company Rocket Connect https://rocketconnect.co.uk/

My talk will be 20 mins.

Cheers, hope to see you there

**Comment by mbuhot** [comment]
Thanks @danstarns! You're the headline for the December meetup: https://www.meetup.com/graphql-sydney/events/297415925/

**Comment by mbuhot** [comment]
Thanks @danstarns, the recording of the presentation is now live on YouTube: https://www.youtube.com/watch?v=rrKD2jw5ZIY&t=18s

**Comment by danstarns** [comment]
Thank you @mbuhot for your great work online and getting the recordings out quickly! 🙏
