### ISSUE TITLE
Better mutations using GraphQL, gRPC, Restful, and in memory altogether

### ISSUE THREAD

**Issue by koresar** [graphqlsydney/graphqlsydney#3]
In that talk I'll go though the common ways of doing mutations and will suggest a simple solution to unify the interface of all your mutations in a human bearable way.

Traditionally, when you change data on the server, or if you validate the frontend data on the backend, your mutations/queries return the mutated data itself, or nothing, or random data structures. And it doesn't matter it it's GraphQL, Restful API, gRPS or even in-process mutation. For example, what would this return? : `userService.updateEmail(oldEmail, newEmail)`
I am going to suggest an idea of interface unification for all your mutations regardless of the protocol or technology you are using.

For: Dec 2019

Full length.

Twitter: https://twitter.com/kore_sar

**Comment by paulfioravanti** [comment]
Thanks, @koresar! Confirmed for tonight!

**Comment by paulfioravanti** [comment]
Thanks for presenting @koresar ! If you want to share your presentation materials, tweet out a link to them at `@graphqlsydney` and we'll give them a retweet.
