### ISSUE TITLE
GraphQL Magic with Angular 

### ISSUE THREAD

**Issue by kuncevic** [graphqlsydney/graphqlsydney#4]
Title: Angular GraphQL Magic 

Description: Do you have GraphQL API that you want to consume in your Angular app? Do you want to learn how to generate services and TypeScript classes ready to be consumed within your Angular app? I will show the best practices how to integrate GraphQL in to your Angular app with 0 lines hand-coded boilerplate. I will demonstrate how to generate all the code your Angular app needs to interact with existing GraphQL server.

Speaker: Aliaksei is a Sydney-based Angular expert. Aliaksei sharing his Angular expertise by consulting dev teams teaching Angular best practices as well as running Angular workshops. Sometimes you can see him presenting Angular-related topics on ngSydney meetup group. Also, Aliaksei is running Sydney-based meetup called Frontend Tech and Angular Minsk meetup based in Belarus. Ref: 

Date: February 2020 

Length: 20-30

Twitter: https://twitter.com/kuncevic

**Comment by paulfioravanti** [comment]
Thanks @kuncevic! You're on for February!

**Comment by paulfioravanti** [comment]
@kuncevic Just a check in to see if you're all set for Thursday. Everything still okay?

**Comment by kuncevic** [comment]
@paulfioravanti yes I am good to go but just altered a title little bit

**Comment by paulfioravanti** [comment]
Thanks so much for the presentation tonight, @kuncevic! If you end up putting your slides online somewhere, please tweet the link at `@graphqlsydney` and we will retweet it.

**Comment by kuncevic** [comment]
@paulfioravanti  just pushed the slides up, here is a twit https://twitter.com/kuncevic/status/1231772509231431680

**Comment by paulfioravanti** [comment]
Thanks, @kuncevic! Re-tweeted!
