### ISSUE TITLE
Scaling GraphQL websites

### ISSUE THREAD

**Issue by sarneaud** [graphqlsydney/graphqlsydney#5]
NB: I want to use a real example from a previous client, but I'm still discussing what they're happy with me saying publicly.

I'd like to give a talk about scaling GraphQL websites.  I hope anyone using GraphQL could learn something from it, but it'll mostly benefit intermediate/advanced users.  I'll talk about the various things you'll need to understand once your site experiences growing pains: HTTP and other network details, website design considerations, caching and the user experience of performance.

I could make it up to a 50min talk, but I can make it 30mins if that fits better.  February, March and April all work for me.

**Comment by paulfioravanti** [comment]
Thanks for the submission, @sarneaud! Love to have the talk, so please update this issue when you have whatever permissions you need from your previous client, and we'll schedule you up!

**Comment by sarneaud** [comment]
Cool.  Feel free to schedule me in now.  I can always talk about networking and stuff without permission :)  It's just a matter of what else I can add.

**Comment by paulfioravanti** [comment]
You got it.

**Comment by paulfioravanti** [comment]
@sarneaud Just a check in to see if you're all set for Thursday. Everything still okay?

**Comment by sarneaud** [comment]
Yep, see you tomorrow.

**Comment by paulfioravanti** [comment]
Thanks for tonight, @sarneaud! If you end up putting your slides online somewhere, please let me know and I'll tweet out the link from the `@graphqlsydney` account.
