### ISSUE TITLE
GraphQL @ :Different

### ISSUE THREAD

**Issue by mehdivk** [graphqlsydney/graphqlsydney#6]
We've been using GraphQL at Different for the past year or so and keen to share our journey so far as GraphQL addresses multiple business/technology problems for us. I would say this is simply a "Success Story" or "Case Study", I would like to share our problems and how we are actively addressing them using GraphQL.

 - Name of talk: GraphQL at Different, a success story
 - Brief: Story of Different and switch from REST to GraphQL
 - Type of talk: Full-length talk (20 mins)

Keen to present during the upcoming Feb meetup or March.

**Comment by paulfioravanti** [comment]
Thanks for the submission, @mehdivk! We already have two full length talks scheduled up for February, and we do the meetup once every two months, so would you be interested in perhaps being on standby for February, but a lock-in for April?

**Comment by mehdivk** [comment]
@paulfioravanti Hi Paul,

No worries. I'm happy to lock-in for the April meetup. FYI, I have presented the same talk at SydJS last month so the content might not be new for some of the audience. Please let me know if you're looking for talks that are fresh from the oven :D

With that being said, I'm going to tweak the talk a little bit to focus on the GraphQL itself rather than Javascript :)

**Comment by paulfioravanti** [comment]
@mehdivk Any content is awesome in my book, and it's always going to be fresh from the oven for someone, so doing your talk in April would be great! Looking forward to seeing the GraphQL-focused version of the talk! Please consider yourself locked in for April! :D

**Comment by mehdivk** [comment]
@paulfioravanti awesome! looking forward to it!

**Comment by paulfioravanti** [comment]
@mehdivk would you be okay with doing this presentation in an online format? For the time being, we're going to be likely doing our meetups over Zoom.

**Comment by mattvalleycodes** [comment]
@paulfioravanti of course. As long as my NBN connection allows me to do so :)

**Comment by mehdivk** [comment]
@paulfioravanti of course. As long as my NBN connections allow me to do so :)

**Comment by paulfioravanti** [comment]
Great! Don't worry, we're all in the same boat with that 😄

**Comment by paulfioravanti** [comment]
Thanks for your talk last night, @mehdivk! If you share your slide deck somewhere online, please tweet it out to `@graphqlsydney` and we'll retweet it.
