### ISSUE TITLE
Feature Flag approach with GraphQL , Apollo and React

### ISSUE THREAD

**Issue by peaonunes** [graphqlsydney/graphqlsydney#9]
I would like to talk about a take on feature flag in GraphQL, exposing it in the schema and highlighting how we can leverage React hooks and Apollo Client features to enhance user experience. 
 
That would be an adaptation of the following post I wrote: https://dev.to/open-graphql/feature-flag-approach-with-graphql-and-react-3l5o

- Feature Flag approach with GraphQL, Apollo and React.
- An exercise on how to expose feature flags in GraphQL and how we can leverage React hooks API and Apollo Client features to enhance user experience.  
- June, 18th.
- 15min ~ 20min would be enough.
- https://twitter.com/peaonunes
- https://twitter.com/peaonunes/photo

**Comment by paulfioravanti** [comment]
Awesome, thanks, @peaonunes! You're locked in for June 18th!

**Comment by paulfioravanti** [comment]
Thanks very much for that talk, @peaonunes, and for sharing your slides!
